/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/oldPc/scene.gltf -t -r public
Author: anarki3000 (https://sketchfab.com/anarki3000)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-pc-f0dca426be374fba96af9675799f9855
Title: Old PC
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_16: THREE.Mesh;
  };
  materials: {
    VoxMaterial_64: THREE.MeshStandardMaterial;
    VoxMaterial_72: THREE.MeshStandardMaterial;
    VoxMaterial_86: THREE.MeshStandardMaterial;
    VoxMaterial_87: THREE.MeshStandardMaterial;
    VoxMaterial_88: THREE.MeshStandardMaterial;
    VoxMaterial_95: THREE.MeshStandardMaterial;
    VoxMaterial_96: THREE.MeshStandardMaterial;
    VoxMaterial_112: THREE.MeshStandardMaterial;
    VoxMaterial_128: THREE.MeshStandardMaterial;
    VoxMaterial_136: THREE.MeshStandardMaterial;
    VoxMaterial_160: THREE.MeshStandardMaterial;
    VoxMaterial_168: THREE.MeshStandardMaterial;
  };
};

export default function OldPc(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/oldPc/scene.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null} scale={2.5}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, 20]}>
          <mesh
            geometry={nodes.Object_5.geometry}
            material={materials.VoxMaterial_64}
          />
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials.VoxMaterial_72}
          />
          <mesh
            geometry={nodes.Object_7.geometry}
            material={materials.VoxMaterial_86}
          />
          <mesh
            geometry={nodes.Object_8.geometry}
            material={materials.VoxMaterial_87}
          />
          <mesh
            geometry={nodes.Object_9.geometry}
            material={materials.VoxMaterial_88}
          />
          <mesh
            geometry={nodes.Object_10.geometry}
            material={materials.VoxMaterial_95}
          />
          <mesh
            geometry={nodes.Object_11.geometry}
            material={materials.VoxMaterial_96}
          />
          <mesh
            geometry={nodes.Object_12.geometry}
            material={materials.VoxMaterial_112}
          />
          <mesh
            geometry={nodes.Object_13.geometry}
            material={materials.VoxMaterial_128}
          />
          <mesh
            geometry={nodes.Object_14.geometry}
            material={materials.VoxMaterial_136}
          />
          <mesh
            geometry={nodes.Object_15.geometry}
            material={materials.VoxMaterial_160}
          />
          <mesh
            geometry={nodes.Object_16.geometry}
            material={materials.VoxMaterial_168}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/oldPc/scene.gltf");
