/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/pc2/pc2.gltf -t -r public
Author: HippoStance (https://sketchfab.com/hippostance)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bm86-portable-pc-d6f9790446eb4ad5bdfb9c537be5d17c
Title: BM86 Portable PC
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    BM86_Portable_BM86_Portable_0: THREE.Mesh;
  };
  materials: {
    BM86_Portable: THREE.MeshStandardMaterial;
  };
};

export default function Pc2(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/pc2/pc2.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null} scale={5}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.008}>
        <mesh
          geometry={nodes.BM86_Portable_BM86_Portable_0.geometry}
          material={materials.BM86_Portable}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/pc2/pc2.gltf");
