/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/retropc2/scene.gltf -t -r public
Author: David Jalbert (https://sketchfab.com/davidjayindie)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/retro-computer-w-floppy-drive-keyboard-4a3fd162531d4dbe9cf00bcdfde4df01
Title: Retro computer w/ floppy drive, keyboard
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ribbon_ribbon_0: THREE.Mesh;
    ribbon_connector_1_connector_0: THREE.Mesh;
    ribbon_connector_2_connector_0: THREE.Mesh;
    ["computer_computer-screen_0"]: THREE.Mesh;
    computer_plastic_0: THREE.Mesh;
    ["computer_connector-female_0"]: THREE.Mesh;
    ["computer_computer-power-led_0"]: THREE.Mesh;
    ["computer_computer-hdd-led_0"]: THREE.Mesh;
    floppy_drive_plastic_0: THREE.Mesh;
    ["floppy_drive_floppy-drive-led_0"]: THREE.Mesh;
    ["floppy_drive_connector-female_0"]: THREE.Mesh;
    ["keyboard-keys_plastic_0"]: THREE.Mesh;
    ["keyboard-keys_keyboard-keys_0"]: THREE.Mesh;
    keyboard_plastic_0: THREE.Mesh;
    ["floppy-slider_metal_0"]: THREE.Mesh;
    floppy_plastic_0: THREE.Mesh;
    ["floppy_floppy-label_0"]: THREE.Mesh;
    ["keyboard-pc-plug_plastic_0"]: THREE.Mesh;
    BezierCurve_plastic_0: THREE.Mesh;
  };
  materials: {
    ribbon: THREE.MeshStandardMaterial;
    connector: THREE.MeshStandardMaterial;
    ["computer-screen"]: THREE.MeshStandardMaterial;
    plastic: THREE.MeshStandardMaterial;
    ["connector-female"]: THREE.MeshStandardMaterial;
    ["computer-power-led"]: THREE.MeshStandardMaterial;
    ["computer-hdd-led"]: THREE.MeshStandardMaterial;
    ["floppy-drive-led"]: THREE.MeshStandardMaterial;
    ["keyboard-keys"]: THREE.MeshStandardMaterial;
    metal: THREE.MeshStandardMaterial;
    ["floppy-label"]: THREE.MeshStandardMaterial;
  };
};

export default function RetroPc2(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/retropc2/scene.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[3.126, 28.473, 6.891]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={100}
      >
        <mesh
          geometry={nodes["computer_computer-screen_0"].geometry}
          material={materials["computer-screen"]}
        />
        <mesh
          geometry={nodes.computer_plastic_0.geometry}
          material={materials.plastic}
        />
        <mesh
          geometry={nodes["computer_connector-female_0"].geometry}
          material={materials["connector-female"]}
        />
        <mesh
          geometry={nodes["computer_computer-power-led_0"].geometry}
          material={materials["computer-power-led"]}
        />
        <mesh
          geometry={nodes["computer_computer-hdd-led_0"].geometry}
          material={materials["computer-hdd-led"]}
        />
      </group>
      <group
        position={[30.139, 3.6, 8.295]}
        rotation={[-Math.PI / 2, 0, -0.311]}
        scale={100}
      >
        <mesh
          geometry={nodes.floppy_drive_plastic_0.geometry}
          material={materials.plastic}
        />
        <mesh
          geometry={nodes["floppy_drive_floppy-drive-led_0"].geometry}
          material={materials["floppy-drive-led"]}
        />
        <mesh
          geometry={nodes["floppy_drive_connector-female_0"].geometry}
          material={materials["connector-female"]}
        />
      </group>
      <group
        position={[3.205, -0.381, 40.706]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      >
        <group
          position={[-0.153, 0.044, 0.05]}
          rotation={[0.175, 0, 0]}
          scale={0.235}
        >
          <mesh
            geometry={nodes["keyboard-keys_plastic_0"].geometry}
            material={materials.plastic}
          />
          <mesh
            geometry={nodes["keyboard-keys_keyboard-keys_0"].geometry}
            material={materials["keyboard-keys"]}
          />
        </group>
        <mesh
          geometry={nodes.keyboard_plastic_0.geometry}
          material={materials.plastic}
        />
      </group>
      <group
        position={[42.35, 1.295, 23.381]}
        rotation={[-Math.PI, -0.436, 0]}
        scale={100}
      >
        <mesh
          geometry={nodes.floppy_plastic_0.geometry}
          material={materials.plastic}
        />
        <mesh
          geometry={nodes["floppy_floppy-label_0"].geometry}
          material={materials["floppy-label"]}
        />
        <mesh
          geometry={nodes["floppy-slider_metal_0"].geometry}
          material={materials.metal}
          position={[0.018, 0, 0]}
        />
      </group>
      <mesh
        geometry={nodes.ribbon_ribbon_0.geometry}
        material={materials.ribbon}
        position={[10.602, 3.701, -18.854]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.ribbon_connector_1_connector_0.geometry}
        material={materials.connector}
        position={[-4.188, 5.039, -8.684]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.ribbon_connector_2_connector_0.geometry}
        material={materials.connector}
        position={[41.604, 1.456, -4.2]}
        rotation={[-Math.PI / 2, 0, 1.105]}
        scale={100}
      />
      <mesh
        geometry={nodes["keyboard-pc-plug_plastic_0"].geometry}
        material={materials.plastic}
        position={[6.638, 5.045, -7.711]}
        rotation={[-Math.PI, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.BezierCurve_plastic_0.geometry}
        material={materials.plastic}
        position={[-26.02, 0.489, 36.853]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/retropc2/scene.gltf");
