/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/spaceman/scene.gltf -t -r public
Author: Tomas Anglim (https://sketchfab.com/tomas.anglim.811)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-spaceman-645a8a97514641e599cdd6ee3d4e4416
Title: Stylized spaceman
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    polySurface130_lambert15_0: THREE.Mesh;
    polySurface130_lambert16_0: THREE.Mesh;
    polySurface130_lambert11_0: THREE.Mesh;
    polySurface130_lambert3_0: THREE.Mesh;
    polySurface130_lambert9_0: THREE.Mesh;
    polySurface130_lambert13_0: THREE.Mesh;
    polySurface130_lambert1_0: THREE.Mesh;
    polySurface130_lambert12_0: THREE.Mesh;
    polySurface130_lambert17_0: THREE.Mesh;
    polySurface130_lambert10_0: THREE.Mesh;
    polySurface130_lambert14_0: THREE.Mesh;
  };
  materials: {
    lambert15: THREE.MeshStandardMaterial;
    lambert16: THREE.MeshStandardMaterial;
    lambert11: THREE.MeshStandardMaterial;
    lambert3: THREE.MeshStandardMaterial;
    lambert9: THREE.MeshStandardMaterial;
    lambert13: THREE.MeshStandardMaterial;
    lambert1: THREE.MeshStandardMaterial;
    lambert12: THREE.MeshStandardMaterial;
    lambert17: THREE.MeshStandardMaterial;
    lambert10: THREE.MeshStandardMaterial;
    lambert14: THREE.MeshStandardMaterial;
  };
};

export default function Spaceman(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/spaceman/scene.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.polySurface130_lambert15_0.geometry}
        material={materials.lambert15}
      />
      <mesh
        geometry={nodes.polySurface130_lambert16_0.geometry}
        material={materials.lambert16}
      />
      <mesh
        geometry={nodes.polySurface130_lambert11_0.geometry}
        material={materials.lambert11}
      />
      <mesh
        geometry={nodes.polySurface130_lambert3_0.geometry}
        material={materials.lambert3}
      />
      <mesh
        geometry={nodes.polySurface130_lambert9_0.geometry}
        material={materials.lambert9}
      />
      <mesh
        geometry={nodes.polySurface130_lambert13_0.geometry}
        material={materials.lambert13}
      />
      <mesh
        geometry={nodes.polySurface130_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        geometry={nodes.polySurface130_lambert12_0.geometry}
        material={materials.lambert12}
      />
      <mesh
        geometry={nodes.polySurface130_lambert17_0.geometry}
        material={materials.lambert17}
      />
      <mesh
        geometry={nodes.polySurface130_lambert10_0.geometry}
        material={materials.lambert10}
      />
      <mesh
        geometry={nodes.polySurface130_lambert14_0.geometry}
        material={materials.lambert14}
      />
    </group>
  );
}

useGLTF.preload("/spaceman/scene.gltf");
