/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/spaceship/spaceship.gltf -t -r public
Author: MisterH (https://sketchfab.com/TGVMisterH)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-moon-landing-v2-7e310f6267e54c9da7a19b88d0b68fb1
Title: The Moon Landing V.2
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_17: THREE.Mesh;
  };
  materials: {
    Rover_Mat: THREE.MeshStandardMaterial;
    Asteroid_Mat: THREE.MeshStandardMaterial;
    Base_Palette_Metallic: THREE.MeshStandardMaterial;
    Base_Palette_Emissive: THREE.MeshStandardMaterial;
    Base_Palette_NonMetal: THREE.MeshStandardMaterial;
    USFlag: THREE.MeshStandardMaterial;
    Astronaut_Suit: THREE.MeshStandardMaterial;
    Astronaut__face: THREE.MeshStandardMaterial;
    Astronaut_Visor: THREE.MeshPhysicalMaterial;
    Material: THREE.MeshStandardMaterial;
  };
};

export default function Spaceship(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/spaceship/spaceship.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} scale={2.5}>
      <group
        position={[1.37, -1.37, -0.021]}
        rotation={[-1.48, 0.078, -2.431]}
        scale={0.103}
      >
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.Rover_Mat}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.Asteroid_Mat}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.Base_Palette_Metallic}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.Base_Palette_Emissive}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.Base_Palette_NonMetal}
        />
        <mesh geometry={nodes.Object_9.geometry} material={materials.USFlag} />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.Astronaut_Suit}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.Astronaut_Suit}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.Astronaut__face}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.Astronaut_Visor}
        />
      </group>
      <group
        position={[1.37, -1.37, -0.021]}
        rotation={[-1.48, 0.078, -2.431]}
        scale={0.103}
      >
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials.Material}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/spaceship/spaceship.gltf");
